apiVersion: v1
kind: Secret
metadata:
  name: karla-magallanes-api-secret
  namespace: karla-magallanes-api-ns
  labels:
    app: karla-magallanes-api

type: Opaque
data:
  username: c2E=
  password: cGFzc3dvcmQ=
