apiVersion: v1
kind: ConfigMap
metadata:
  name: karla-magallanes-api-config
  namespace: karla-magallanes-api-ns
  labels:
    app: karla-magallanes-api

data:
  APP_ENV: "produccion"
  APP_PORT: "8085"
  APP_VERSION: "1.0.0"
