apiVersion: v1
kind: Service
metadata:
  name: karla-magallanes-api-service
  namespace: karla-magallanes-api-ns
  labels:
    app: karla-magallanes-api
spec:
  selector:
    app: karla-magallanes-api
  type: NodePort
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 30080
